### PR TITLE
ADIOS2: Update to 2.9.1

### PR DESCRIPTION
**Pull request by eschnett**
Also simplify HDF5 configuration.

### CODE REVIEW

**Comment by rhaas80** [comment]
Uh, now it seems as if it is no longer turning off building with HDF5 support.  That is:

```
if [ -n "${HAVE_CAPABILITY_HDF5}" ]; then
    ADIOS2_HDF5_OPTS="-DHDF5_ROOT=${HDF5_DIR} -DADIOS2_USE_HDF5=ON"
else
    ADIOS2_HDF5_OPTS="-DADIOS2_USE_HDF5=OFF"
fi 
```

remains. My guess is that we need to keep `-DADIOS2_USE_HDF5=OFF` to avoid ADIOS2's cmake code auto-detecting HDF5 on clusters and building against it (and possibly pulling in an unexpected HDF5 version this way). Also the HDF5 options in `configuration.ccl` remain originally `HDF5` was found in

```
configuration.ccl
dist/ADIOS2-2.9.0.tar
dist/hdf5_version.patch
src/build.sh
src/make.code.deps
```

and it should be removed from all of them if all HDF5 support is removed. 

I'll make an extra commit.

**Comment by eschnett** [comment]
After I removed the HDF5 patches HDF5 was building fine for me, that’s why
I didn’t turn it off.

-erik

**Comment by rhaas80** [comment]
I see. I would guess (based on commit history in ADIOS) that the patch became unnecessary in ADIOS 2.9.0. Interestingly it does compile and link for me (gcc-12.3.0, HDF5-1.12 compiled form tar file in ExternalLibraries/HDF5) with ADIOS 2.9.1 and HDF5 1.12 both with or without the patches (that is both git hash 1cf9036 and hash c393568. Looking at the ADIOS2 code in  source/adios2/toolkit/interop/hdf5/HDF5Common.cpp:

```
#if H5_VERSION_GE(1, 11, 0)
#if (defined H5_USE_16_API || defined H5_USE_18_API)
    herr_t ret = H5Oget_info(m_FileId, &oinfo);
#else
    herr_t ret = H5Oget_info(m_FileId, &oinfo, H5O_INFO_ALL);
#endif
#else
    herr_t ret = H5Oget_info(m_FileId, &oinfo);
#endif
```
together with 
```
#define H5_USE_112_API_DEFAULT 1
```
in `configs/sim/scratch/external/HDF5/include/H5pubconf.h` has me scratching my head. Namely this should not compile for HDF5 >= 1.11.0 unless `H5_USE_16_API`  or  `H5_USE_18_API` are set (they are not as far as I can tell).

Though I am not sure why this compiles actually even if it was to us the 3 argument version. Namely for the 1.12 API it defines (H5version.h lin 991)

```
#if !defined(H5Fget_info_vers) || H5Fget_info_vers == 2
  #ifndef H5Fget_info_vers
    #define H5Fget_info_vers 2
  #endif /* H5Fget_info_vers */
  #define H5Fget_info H5Fget_info2
  #define H5F_info_t H5F_info2_t
#elif H5Fget_info_vers == 1
  #define H5Fget_info H5Fget_info1
  #define H5F_info_t H5F_info1_t
#else /* H5Fget_info_vers */
  #error "H5Fget_info_vers set to invalid value"
#endif /* H5Fget_info_vers */
```
that is `#define H5F_info_t H5F_info2_t` but the actual prototype for `H5Fget_info2` in `H5Opublic.h` is
```
H5_DLL herr_t H5Oget_info2(hid_t loc_id, H5O_info1_t *oinfo, unsigned fields);
```
that is, it uses `H5O_info1_t`, the wrong type.

**Comment by rhaas80** [comment]
Ah, I was looking at the wrong function `H5Fget_info_vers` instead of `H5Oget_info_vers` which explains why things work with or without the patch.

**Pull request merged**
